[build]
  base = "frontend"
  command = "CI= npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables not needed - using smart detection in api.js
# The app will automatically detect which backend to use based on the frontend URL