[tool.black]
line-length = 88
target-version = ['py39', 'py310', 'py311', 'py312']

[tool.pylint.messages_control]
disable = "C0111,C0103,R0903,R0913,W0622"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true

[tool.ruff]
line-length = 88
select = ["E", "F", "I"]
ignore = ["E501"]

[tool.coverage.run]
source = ["src"]
omit = ["*/tests/*", "*/test_*.py"]