// backend/src/core/bot-brains/playInference.js
//
// Reading the table: how likely were the plays we have SEEN, if a sampled
// world is the true one? (Opus 5.5, Sept 2026.)
//
// A search brain samples hidden worlds from public information and then
// treats every one as equally real. But the other seats have been telling us
// about their hands all round: a seat that ducked under an opponent's ace
// with a jack probably had nothing lower, a defender who did not schmear
// onto a partner's secure trick probably had no points in that suit, a
// bidder who led a small side card while holding the boss trump is unusual.
// This module turns that into a number. It replays the round's history in a
// world, and at every play another seat made asks a model of card play — one
// that sees ONLY what that seat could see (its own hand, the cards already
// played, the trick in front of it) — how likely that card was. The product
// of those probabilities is the world's likelihood; the brain keeps the
// worlds that explain the table best.
//
// Nothing here reads a hand the bot cannot see. The world is the bot's own
// guess; the history is public (PublicRoundView.tricks). The model is a
// multinomial logit over a handful of features of each legal card, fitted by
// scripts/fit-play-model.js on the decisions of every brain we have, and mixed
// with a uniform floor (EPSILON) so a player who does something odd — humans
// do — makes a world less likely, never impossible.
//
// Card representation is ravenSearch's: suit * 9 + rank, suits H D C S, ranks
// 6 7 8 9 J Q K 10 A = 0..8, hands as four 9-bit masks, three active seats.

'use strict';

const search = require('./ravenSearch');

const RANK_PTS = search.RANK_PTS;
const FULL = 0x1FF;

let MODEL = null;
try {
    // Generated by scripts/fit-play-model.js. PLAY_MODEL_PATH lets a
    // simulator audition another fit.
    MODEL = require(process.env.PLAY_MODEL_PATH || './playModel.json');
} catch (error) { /* no fit yet: every play is equally likely */ }

const FEATURES = [
    // following
    'beatStand', 'beatNoStand', 'beatStandPts', 'beatTrickPts', 'beatRank',
    'ruff', 'overtakePartner',
    'schmearSecure', 'schmearInsecure', 'dumpToOpp', 'followRank', 'offSuitPts', 'offSuitTrump',
    // leading
    'leadBoss', 'leadBossPts', 'leadPts', 'leadTrump', 'leadTrumpBidder', 'leadLen', 'leadRank',
    'leadTenUnderAce', 'leadSingleton',
];

const popcount = (m) => {
    let n = 0;
    while (m) { m &= m - 1; n += 1; }
    return n;
};

// Nothing unknown to the actor in suit s ranks above r.
const isBoss = (unknown, s, r) => ((unknown[s] >> (r + 1)) & FULL) === 0;

/**
 * Feature vectors for every legal card of the seat to act.
 * ctx: { hand: [4 masks] (actor's), played: [4 masks] (every card played so
 *        far, the live trick included), plays: [{p, s, r}] live trick,
 *        trump, broken, bidder, actor }
 * Returns { cards: [idx], feats: [Float64Array] }.
 */
function cardFeatures(ctx) {
    const { hand, played, plays, trump, broken, bidder, actor } = ctx;
    const unknown = [0, 1, 2, 3].map(s => FULL & ~(hand[s] | played[s]));
    const cards = [];
    const feats = [];
    const nf = FEATURES.length;
    const mySide = actor === bidder ? 1 : 0;

    if (plays.length === 0) {
        const hasNonTrump = [0, 1, 2, 3].some(s => s !== trump && hand[s]);
        for (let s = 0; s < 4; s += 1) {
            if (!hand[s]) continue;
            if (!broken && hasNonTrump && s === trump) continue;
            let m = hand[s];
            const len = popcount(hand[s]);
            while (m) {
                const r = 31 - Math.clz32(m & -m);
                m &= m - 1;
                const f = new Float64Array(nf);
                const pts = RANK_PTS[r] / 11;
                const boss = isBoss(unknown, s, r);
                f[13] = boss ? 1 : 0;
                f[14] = boss ? pts : 0;
                f[15] = boss ? 0 : pts;
                f[16] = s === trump ? 1 : 0;
                f[17] = s === trump && actor === bidder ? 1 : 0;
                f[18] = len / 9;
                f[19] = r / 8;
                f[20] = r === 7 && (unknown[s] & (1 << 8)) ? 1 : 0;
                f[21] = len === 1 && s !== trump ? 1 : 0;
                cards.push(s * 9 + r);
                feats.push(f);
            }
        }
        return { cards, feats };
    }

    const lead = plays[0].s;
    // Current winner of the trick.
    let winP = -1; let winS = -1; let winR = -1; let trickPts = 0;
    for (const play of plays) {
        trickPts += RANK_PTS[play.r];
        const beats = winP === -1
            || (play.s === trump ? (winS !== trump || play.r > winR) : (winS !== trump && play.s === lead && play.r > winR));
        if (beats) { winP = play.p; winS = play.s; winR = play.r; }
    }
    const seatsAfter = 2 - plays.length;
    const amLast = seatsAfter === 0;
    const nextSeat = (actor + 1) % 3;
    const nextIsPartner = seatsAfter === 1 && ((nextSeat === bidder ? 1 : 0) === mySide);
    const partnerWinning = (winP === bidder ? 1 : 0) === mySide;
    // A card is safe once played when nobody left to act against me can
    // take it — as far as the actor can tell: last to play, or only a
    // partner behind, or the boss of its suit among the cards unseen.
    const standsAt = (s, r) => amLast || nextIsPartner || isBoss(unknown, s, r);
    const partnerSecure = partnerWinning && (amLast || standsAt(winS, winR));

    let legalMask = null;
    if (hand[lead]) legalMask = [[lead, hand[lead]]];
    else if (hand[trump]) legalMask = [[trump, hand[trump]]];
    else legalMask = [0, 1, 2, 3].filter(s => hand[s]).map(s => [s, hand[s]]);

    for (const [s, mask] of legalMask) {
        let m = mask;
        while (m) {
            const r = 31 - Math.clz32(m & -m);
            m &= m - 1;
            const f = new Float64Array(nf);
            const pts = RANK_PTS[r] / 11;
            const beats = s === trump ? (winS !== trump || r > winR) : (winS !== trump && s === lead && r > winR);
            if (beats && !partnerWinning) {
                const stands = standsAt(s, r);
                f[0] = stands ? 1 : 0;
                f[1] = stands ? 0 : 1;
                f[2] = stands ? pts : 0;
                f[3] = trickPts / 30;
                f[4] = r / 8;
            }
            if (s === trump && lead !== trump) f[5] = 1;
            if (beats && partnerWinning) f[6] = 1;
            if (partnerWinning && !beats) {
                if (partnerSecure) f[7] = pts; else f[8] = pts;
            }
            if (!partnerWinning && !beats) f[9] = pts;
            f[10] = r / 8;
            if (s !== lead && s !== trump) { f[11] = pts; }
            if (s !== lead && s === trump) f[12] = 1;
            cards.push(s * 9 + r);
            feats.push(f);
        }
    }
    return { cards, feats };
}

const WEIGHTS = () => (MODEL && MODEL.weights ? MODEL.weights : null);

// log P(card | ctx) under the fitted logit, mixed with a uniform floor.
function logProb(ctx, card, weights, epsilon) {
    const { cards, feats } = cardFeatures(ctx);
    const n = cards.length;
    if (n <= 1) return 0;
    const at = cards.indexOf(card);
    if (at === -1) return -30; // illegal in this world: effectively impossible
    let max = -Infinity;
    const z = new Float64Array(n);
    for (let i = 0; i < n; i += 1) {
        let v = 0;
        const f = feats[i];
        for (let k = 0; k < f.length; k += 1) if (f[k] !== 0) v += weights[k] * f[k];
        z[i] = v;
        if (v > max) max = v;
    }
    let sum = 0;
    for (let i = 0; i < n; i += 1) sum += Math.exp(z[i] - max);
    const p = Math.exp(z[at] - max) / sum;
    return Math.log((1 - epsilon) * p + epsilon / n);
}

/**
 * Log-likelihood of the public history in one sampled world.
 *   view   PublicRoundView (tricks, playedBy, activeNames, bidder, trump)
 *   world  sampleWorld() result: current hands of every seat
 *   opts   { epsilon, weights, skip: Set of seat names not scored }
 * Only plays by seats in neither `skip` nor the bot's own seat are scored.
 */
function historyLogLikelihood(view, world, opts = {}) {
    const weights = opts.weights || WEIGHTS();
    if (!weights || !view.tricks) return 0;
    const epsilon = Number.isFinite(opts.epsilon) ? opts.epsilon : 0.1;
    const seats = view.activeNames;
    if (seats.length !== 3) return 0;
    const trump = search.SUIT_IDX[view.trumpSuit];
    const bidder = seats.indexOf(view.bidderName);
    const me = seats.indexOf(view.botName);

    // Rebuild each seat's hand at the start of play: what it holds now in
    // this world plus everything it has played.
    const hands = seats.map((name) => {
        const masks = [0, 0, 0, 0];
        for (const card of [...(world.hands[name] || []), ...(view.playedBy[name] || [])]) {
            const idx = search.cardIdx(card);
            masks[(idx / 9) | 0] |= 1 << (idx % 9);
        }
        return masks;
    });
    const played = [0, 0, 0, 0];
    let broken = false;
    let ll = 0;
    for (const trick of view.tricks) {
        const plays = [];
        for (const { playerName, card } of trick.plays) {
            const p = seats.indexOf(playerName);
            const idx = search.cardIdx(card);
            const s = (idx / 9) | 0;
            const r = idx % 9;
            if (p !== me && !(opts.skip && opts.skip.has(playerName))) {
                ll += logProb({ hand: hands[p], played, plays, trump, broken, bidder, actor: p }, idx, weights, epsilon);
            }
            hands[p][s] &= ~(1 << r);
            played[s] |= 1 << r;
            plays.push({ p, s, r });
            if (s === trump) broken = true;
        }
    }
    return ll;
}

module.exports = { FEATURES, cardFeatures, logProb, historyLogLikelihood, MODEL: () => MODEL };
